version: '2'

volumes:
 app_nextcloud:
 db_nextcloud:

services:
 web:
   image: nginx
   volumes:
     - ./data/html:/var/www/html
   links:
     - app
   volumes_from:
     - app
   environment:
     - VIRTUAL_HOST
   networks:
   - back
   - lb_web
   ports:
     - 80:80
     - 443:443
 db_nextcloud:
   image: mariadb
   restart: always
   volumes:
     - ./data/mariadb:/var/lib/mysql
   environment:
     - MYSQL_DATABASE=nextcloud
     - MYSQL_USER=nextcloud
     - MYSQL_ROOT_PASSWORD=admin
   ports:
     - "3306:3306"
 app_nextcloud:
   image: nextcloud
   ports:
     - "8080:80"
   links:
     - db_nextcloud
   volumes:
     - ./data/nextcloud:/var/www/html
   restart: always
