version: '3'
services:
  nginx:
       # build: ./containers/nginx
       #restart: always
    image  : nginx
    ports  :
        - "80:80"
    volumes:
       #- ./public:/usr/share/nginx/html
        - ./data/html /var/www/html
