version: '2'

services:
  db:
    image: mariadb #pull from docker-test
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress

      restart: always

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
    #- ./public:/usr/share/nginx/html
      - ./data/html:/var/www/html

    restart: always

    wordpress:
      depends_on:
        - db
      image: wordpress:latest
      links:
        - db
      ports:
        - "8000:80"
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_PASSWORD: wordpress

      restart: always

    #  app:
    #    image: nextcloud
    #    links:
    #      - db
    #    ports:
    #      - "8081:80"
    #    volumes:
    #      - ./data/nextcloud:/var/www/html
    #    restart: always

    #   db:
    #     image: mysql
    #     volumes:
    #       - "./.data/db:/var/lib/mysql"
    #     environment:
    #       MYSQL_ROOT_PASSWORD: wordpress
    #       MYSQL_DATABASE: wordpress
    #       MYSQL_USER: wordpress
    #       MYSQL_PASSWORD: wordpress
    #     #restart: always
